#!/usr/bin/env pwsh

Import-Module -NoClobber -Name "MnCommonPsToolLib.psm1"; Set-StrictMode -Version Latest; trap [Exception] { StdErrHandleExc $_; break; }

function UnitTest_Tool(){
  OutProgress (ScriptGetCurrentFuncName);
  #
  if( "TEST_THIS_IS_NOT_NESSESSARY" -eq "" ){  ToolTailFile "./anyfile.log"; }
  #
  if( "TEST_THIS_IS_NOT_NESSESSARY" -eq "" ){  ToolAddLineToConfigFile "./myconfigfile.cfg" "MyVar=`"MyValue`"; # AUTOGENERATED-DO-NOT-CHANGE"; }
  #
  ToolGithubApiAssertValidRepoUrl "https://github.com/mniederw/MnCommonPsToolLib/";
  #
  function Test_ToolFileNormalizeNewline(){
    [String] $src = FileGetTempFile; FileWriteFromString $src "Ä`r`nB" $true -traceCmd:$true; Assert ((FileReadContentAsString $src "Default") -eq "Ä`r`nB");
    [String] $tar = FileGetTempFile;
    if( -not (ProcessIsLesserEqualPs5) ){ # TODO in ps5 it fails, # TODO: try to replace Default by UTF8.
      ToolFileNormalizeNewline $src $tar $true                             -traceCmd:$true; Assert ((FileReadContentAsString $tar "Default") -eq "Ä$([Environment]::NewLine)B");
      ToolFileNormalizeNewline $src $tar $true  "UTF8BOM" "`n"   "Default" -traceCmd:$true; Assert ((FileReadContentAsString $tar "Default") -eq "Ä`nB");
      ToolFileNormalizeNewline $src $tar $true  "UTF8BOM" "`n"   "UTF8"    -traceCmd:$true; Assert ((FileReadContentAsString $tar "Default") -eq "Ä`nB");
      ToolFileNormalizeNewline $src $tar $true  "UTF8BOM" "`r`n"           -traceCmd:$true; Assert ((FileReadContentAsString $tar "Default") -eq "Ä`r`nB");
      ToolFileNormalizeNewline $src $tar $true  "UTF8"    "`r`n"           -traceCmd:$true; Assert ((FileReadContentAsString $tar "UTF8"   ) -eq "Ä`r`nB");
    }
  } Test_ToolFileNormalizeNewline;
  #
  [String] $srcFile = FileGetTempFile     ; FileWriteFromString $srcFile           "hello world" $true -traceCmd:$true;
  [String] $srcDir  = DirCreateTemp "MN7z"; FileWriteFromString "$srcDir/test.txt" "hello world" $true -traceCmd:$true;
  [String] $tar7zipFile1 = "$srcFile.7z";
  [String] $tar7zipFile2 = "$srcFile.7z";
  ToolCreate7zip $srcFile $tar7zipFile1; Assert ((FileGetSize $tar7zipFile1) -gt 0);
  ToolCreate7zip $srcDir  $tar7zipFile2; Assert ((FileGetSize $tar7zipFile2) -gt 0);
  FileDelete $tar7zipFile1;
  FileDelete $tar7zipFile2;
  FileDelete $srcFile;
  DirDelete  $srcDir;
  #
  # ToolUnzip ( [String] $srcZipFile, [String] $tarDir ){ # tarDir is created if it not exists, no overwriting,.  Is currently tested in: ToolGithubApiDownloadLatestReleaseDir
  #
  try{
    ToolGithubApiListOrgRepos "TheAlgorithms"  | Where-Object{ -not $_.archived -and -not $_.private } |
      Select-Object Url, default_branch, fork, forks, language, CreatedAt, UpdatedAt, PermAdm, PermPush, PermPull, LicName, Description -First 3;
    [String] $tmpDir = ToolGithubApiDownloadLatestReleaseDir "https://github.com/mniederw/MnCommonPsToolLib/"; Assert ($tmpDir.Length -gt 5);
  }catch{ # Response status code does not indicate success: 403 (rate limit exceeded). Or: curl: (56) The requested URL returned error: 403
    [String] $msg = $_.Exception.Message;
    if( -not ($msg.Contains("403 (rate limit exceeded)") -or $msg.Contains("The requested URL returned error: 403")) ){ throw; }
    OutWarning "Warning: Sometimes we get 403 (rate limit exceeded). Ignored: $_.Exception.Message";
  }
  #
  AssertIsEmpty (ToolNpmFilterIgnorableInstallMessages @(""
    ,"added 4 packages in 2s";
    ,"added 1 package, and changed 113 packages in 11s"
    ,"changed 108 packages in 9s";
    ,"removed 1 package, and changed 113 packages in 11s"
    ,"found 0 vulnerabilities"
    ,"up to date, audited 5 packages in 913ms"
    ,"up to date, audited 6 packages in 1s"
    ,"1 package is looking for funding"
    ,"6 packages are looking for funding"
    ,'run `npm fund` for details'
    ,'Run `npm audit` for details.'
    ,"3 critical severity vulnerabilities"
    ,"To address issues that do not require attention, run:"
    ,"npm audit fix"
    ,"Some issues need review, and may require choosing"
    ,"a different dependency."
  ) );
  if( "TEST_THIS_IS_NOT_NESSESSARY" -eq "" ){ Assert (FileExists (ToolEvalExecForVsCode)); }
}
UnitTest_Tool;
